@startuml EasyRide_Domain_Model

title EasyRide Domain Model

left to right direction

skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam linetype ortho
skinparam class {
  BackgroundColor #FFF8C6
  BorderColor #111111
  ArrowColor #111111
}

class Employee {
  - name
  - password
}

class EasyRide {
  - customers
  - vehicles
  - bookings
}

class Customer {
  - name
  - phoneNo
  - email
  - cpr
  - passportNo
  - licenseNo
}

class DrivingLicense {
  - isCategoryA
  - isCategoryB
  - isCategoryC
  - isCategoryD
}

class Booking {
  - startDate
  - endDate
  - actualReturnDate
  - bookingStatus
}

class Vehicle {
  - model
  - color
  - engine
  - plateNo
  - priceHour
  - deposit
  - noOfTire
  - lateFee
  - requiredLicense
  - condition
  - noOfSeats
  - currentState
}

interface VehicleState

class AvailableState
class RentedState

class Car
class MotorCycle {
  - hasSidecar
  - type
}

class Van {
  - cargoVolume
  - hasSlidingDoor
}

class Truck {
  - loadCapacity
  - trailerAttached
}

class SportsCar {
  - topSpeed
  - hasTurbo
}

EasyRide "1" -- "0..*" Customer : has
EasyRide "1" -- "1..*" Vehicle : has
EasyRide "1" -- "0..*" Booking : has

Employee "1" -- "1" EasyRide : uses

Customer "1" -- "0..*" Booking : makes
Customer "1" -- "1" DrivingLicense : has

Vehicle "1" -- "0..*" Booking : is booked in

Vehicle "1" -- "1" VehicleState : has

VehicleState <|.. AvailableState
VehicleState <|.. RentedState

Vehicle <|-- Car
Vehicle <|-- MotorCycle
Vehicle <|-- Van
Vehicle <|-- Truck
Vehicle <|-- SportsCar

Employee -[hidden]right- EasyRide
EasyRide -[hidden]right- Customer
Customer -[hidden]right- Booking
Booking -[hidden]right- Vehicle
Vehicle -[hidden]down- VehicleState
Vehicle -[hidden]down- Car
Car -[hidden]right- MotorCycle
MotorCycle -[hidden]right- Van
Van -[hidden]right- Truck
Truck -[hidden]right- SportsCar

@enduml
