@startuml
title Activity Diagram - Create Booking

start

:Select Create Booking;
:Select registered customer;
:Enter rental period;
:Display available vehicles;

if (Vehicles available?) then (Yes)

repeat
    if (Filter vehicles?) then (Yes)
        :Filter vehicles;
        :Display updated vehicle list;
    endif

    :Select vehicle;
    :Verify vehicle availability;

    if (Vehicle available?) then (Yes)
        break
    else (No)
        :Inform vehicle is no longer available;
        :Display available vehicles;
    endif

repeat while (Vehicle unavailable?)

if (Confirm booking?) then (Confirm)
    :Create booking;
    :Reserve vehicle;
else (Cancel)
    :Cancel booking process;
endif

else (No)
    :Inform no vehicles are available;
endif

stop

@enduml